# Website designed by Olivia Wikle (https://github.com/owikle).

title: Nathan B. Wikle
author: Nathan Wikle

# url is your gh-pages base, following the pattern: username.github.io
url: https://nbwikle.github.io

# personal urls
bio: "Assistant Professor, Department of Statistics and Actuarial Science, University of Iowa"
email: nathan-wikle@uiowa.edu
github: https://github.com/nbwikle
school: https://stat.uiowa.edu/
orcid: https://orcid.org/0000-0001-8574-8752


# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: true
