# Website created by Olivia Wikle (https://github.com/owikle).

title: Nathan B. Wikle
author: Nathan Wikle

# url is your gh-pages base, following the pattern: username.github.io
url: https://nbwikle.github.io

# personal urls
bio: "Nathan is a statistician"
email: nbwikle@psu.edu
github: https://github.com/nbwikle
school: https://science.psu.edu/stat
orcid: https://orcid.org/0000-0001-8574-8752


# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: true
