# Website designed by Olivia Wikle (https://github.com/owikle).

title: Nathan B. Wikle
author: Nathan Wikle

# url is your gh-pages base, following the pattern: username.github.io
url: https://nbwikle.github.io

# personal urls
bio: "Postdoctoral Fellow, Department of Statistics and Data Science, University of Texas at Austin"
email: nathan.wikle@austin.utexas.edu
github: https://github.com/nbwikle
school: https://stat.utexas.edu/
orcid: https://orcid.org/0000-0001-8574-8752


# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: true
